addSbtPlugin("com.github.sbt" % "sbt-native-packager" % "1.9.16")
addSbtPlugin("com.github.sbt" % "sbt-javaagent"       % "0.1.8")
addSbtPlugin("io.kamon"       % "sbt-kanela-runner"   % "2.1.0")
addSbtPlugin("org.scalameta"  % "sbt-scalafmt"        % "2.5.2")
addSbtPlugin("org.typelevel"  % "sbt-tpolecat"        % "0.5.1")
addSbtPlugin("ch.epfl.scala"  % "sbt-scalafix"        % "0.12.0")
addSbtPlugin("nl.gn0s1s"      % "sbt-dotenv"          % "3.0.0")
