addSbtPlugin("org.typelevel"  % "sbt-tpolecat"       % "0.5.0")
addSbtPlugin("org.scalameta"  % "sbt-scalafmt"       % "2.5.2")
addSbtPlugin("nl.gn0s1s"      % "sbt-dotenv"         % "3.0.0")
addSbtPlugin("io.kamon"       % "sbt-kanela-runner"  % "2.0.14")
addSbtPlugin("com.github.sbt" % "sbt-native-packager" % "1.9.16")
